# GitHub Action, die aus den LiaScript-Materialien des Sommersemester 2020 ein
# Skript generiert
name: GeneratePdf

# Hier legen wir den Trigger f체r die Action fest.
# "Wenn ein Push auf dem branch SoSe2020 realisert wird, werden die
# nachfolgenden Schritte ausgef체hrt"
on:
  push:
    branches:
      - SoSe2020_generation

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    container: mirisbowring/texlive_ctan_full
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          ref: SoSe2020
        # Hier ist es jetzt etwas kniffliger. Wir wollen an pandoc eine Liste
        # alle relevanten Dateien 체bergeben. Dazu brauchen wir eine sogenannte
        # Umgebungsvariable die wir FILELIST nennen. Ihr werden alle Dateinamen
        # zugewiesen, die auf mdx enden.
      - name: Run preprocessing and set environment variables
        run : |
          python3 .github/workflows/preprocessing.py
          echo ::set-env name=FILELIST::$(ls *.mdx)
          mkdir output
        # Aufruf eines Standard-Docker Containers, in dem pandoc (und Latex)
        # l채uft.
      - name: Install pandoc
        run: |
          sudo apt install pandoc
